import Link from 'next/link';
import { BarChart3, Brain, Target, Database, Activity, ShieldAlert, Check } from 'lucide-react';
import LeadCaptureForm from './components/LeadCaptureForm';

const faq = [
  {
    q: 'What is Generative Engine Optimization (GEO)?',
    a: "Generative Engine Optimization (GEO) is the practice of optimizing your brand's content so that AI models—ChatGPT, Google Gemini, Anthropic Claude, and Perplexity—cite your brand as the authoritative source when users ask questions in your industry. Unlike traditional SEO, which targets ranked search results, GEO targets the AI-generated answers that now appear before those results.",
  },
  {
    q: 'How is GEO different from traditional SEO?',
    a: 'SEO optimizes for ranked blue links in search engines. GEO optimizes for zero-click AI answers generated by large language models. When a user asks ChatGPT "What is the best enterprise security software?", GEO determines whether your brand is named, cited, or recommended in that AI response—without the user ever visiting a search results page.',
  },
  {
    q: 'What is AI Share of Voice (A-SOV)?',
    a: 'AI Share of Voice (A-SOV) measures how often your brand is mentioned or recommended by AI models relative to your competitors, across a standardized set of industry queries. Auspexi tracks your A-SOV daily across ChatGPT, Google Gemini, Anthropic Claude, and Perplexity AI.',
  },
  {
    q: 'What are Cite-Magnet Facts?',
    a: "Cite-Magnet Facts are high-entropy, statistically specific claims that AI models preferentially cite in their responses. Auspexi's Fact-Vault identifies, scores, and distributes these facts across your content channels to maximise the likelihood of AI citation.",
  },
];

const features = [
  { icon: BarChart3, name: 'AI Share of Voice Tracker', desc: 'Measure how often ChatGPT, Gemini, Claude and Perplexity cite your brand versus competitors across thousands of industry queries. Updated daily.' },
  { icon: Brain, name: 'Citacious AI Analyst', desc: 'A dedicated GEO AI analyst that monitors your dashboard, interprets drift signals, and drafts corrective content strategies in real time.' },
  { icon: Target, name: 'Cite-Magnet Fact Injection', desc: 'Extract and inject high-entropy statistical facts into your content—the specific claims AI models prefer to cite as primary sources.' },
  { icon: Database, name: 'Fact-Vault', desc: "A structured library of your brand's highest-value, AI-citation-ready facts, entropy-scored and amplified across six content platforms." },
  { icon: Activity, name: 'Z-Score Sentiment Drift Detection', desc: 'Statistical anomaly detection that flags when AI model sentiment toward your brand shifts beyond normal variance—before it becomes a reputational crisis.' },
  { icon: ShieldAlert, name: 'Brand Monitor', desc: 'Real-time monitoring of brand mentions across Reddit, Quora and forum threads, with context-poisoning risk scoring and counter-narrative recommendations.' },
];

const plans = [
  {
    name: 'Starter', price: '$149', desc: 'For solo founders & early-stage teams',
    features: ['Track 1 Brand, 5 Keywords', 'Monthly AI SOV Snapshot', '1 GB Fact-Vault Storage', 'Basic Latent Space Map', 'Weekly Email Reports'],
  },
  {
    name: 'Pro', price: '$499', desc: 'For growth teams & marketing managers', highlighted: true,
    features: ['Track 5 Brands, 50 Keywords', 'Full Neural Latent Map', '25-Competitor Radar', 'Z-Score Drift Alerts', '10 GB Fact-Vault', '12-Month Context Memory'],
  },
  {
    name: 'Business', price: '$1,899', desc: 'For mid-market SaaS & high-growth brands',
    features: ['Track 25 Brands, 250 Keywords', 'Full API Access', 'Autonomous Social Seeding', '50 GB Fact-Vault', 'Priority Support & Onboarding', 'White-Label Reporting'],
  },
];

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'SoftwareApplication',
      '@id': 'https://auspexi.com/#app',
      name: 'Auspexi',
      applicationCategory: 'BusinessApplication',
      description: 'Generative Engine Optimization (GEO) platform tracking brand AI Share of Voice across ChatGPT, Gemini, Claude and Perplexity.',
      url: 'https://auspexi.com',
      image: 'https://auspexi.com/geo-infographic.png',
      offers: { '@type': 'AggregateOffer', priceCurrency: 'USD', lowPrice: '149', highPrice: '4999' },
    },
    {
      '@type': 'FAQPage',
      mainEntity: faq.map(({ q, a }) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    },
  ],
};

export default function HomePage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <div className="min-h-screen bg-[#050505] text-white">

        {/* Nav */}
        <header className="sticky top-0 z-50 border-b border-white/5 bg-[#050505]/80 backdrop-blur-sm">
          <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
            <Link href="/" className="text-xl font-bold tracking-tight">Auspexi</Link>
            <nav className="hidden md:flex items-center gap-8">
              <a href="#features" className="text-sm text-zinc-400 hover:text-white transition">Features</a>
              <a href="#pricing" className="text-sm text-zinc-400 hover:text-white transition">Pricing</a>
              <Link href="/blog" className="text-sm text-zinc-400 hover:text-white transition">Blog</Link>
              <Link href="/roadmap" className="text-sm text-zinc-400 hover:text-white transition">Roadmap</Link>
            </nav>
            <Link href="/dashboard" className="h-9 px-4 rounded-lg bg-white text-black text-sm font-semibold hover:bg-zinc-200 transition flex items-center">
              Sign In
            </Link>
          </div>
        </header>

        {/* Hero — server-rendered for Google crawl */}
        <section className="relative py-32 lg:py-48 px-6 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-b from-pink-500/5 via-transparent to-transparent pointer-events-none" />
          <div className="max-w-4xl mx-auto relative z-10 text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-pink-500/10 border border-pink-500/20 text-pink-400 text-sm font-medium mb-6">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-pink-400 opacity-75" />
                <span className="relative inline-flex rounded-full h-2 w-2 bg-pink-500" />
              </span>
              The AI Search Era Has Arrived
            </div>
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-6 leading-tight">
              Generative Engine{' '}
              <span className="bg-gradient-to-r from-pink-500 to-pink-400 bg-clip-text text-transparent">Optimization</span>{' '}
              for AI Search
            </h1>
            <p className="text-xl text-zinc-300 mb-4 max-w-2xl mx-auto leading-relaxed">
              Traditional SEO is dying. Auspexi is the premier <strong>Generative Engine Optimization (GEO)</strong> platform that ensures your brand is cited, recommended, and prioritized by AI models like ChatGPT, Gemini, and Claude.
            </p>
            <p className="text-base text-zinc-500 mb-10 max-w-xl mx-auto">
              Track your AI Share of Voice. Inject cite-magnet facts. Detect sentiment drift. All in one dashboard.
            </p>
            <LeadCaptureForm />
            <p className="mt-4 text-xs text-zinc-600">Free report — no credit card required.</p>
          </div>
        </section>

        {/* What is GEO — optimised for featured snippets */}
        <section className="py-20 px-6 border-t border-white/5">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl font-bold mb-6 text-center">What is Generative Engine Optimization?</h2>
            <p className="text-zinc-300 text-lg leading-relaxed mb-4">
              <strong>Generative Engine Optimization (GEO)</strong> is the practice of optimizing your brand&apos;s digital presence so that large language models cite your brand as the primary, authoritative source when users ask questions in your industry.
            </p>
            <p className="text-zinc-400 leading-relaxed mb-4">
              Unlike traditional SEO—which targets ranked blue links—GEO targets the AI-generated answers that now appear at the top of Google AI Overviews, within ChatGPT, and across Perplexity AI. When a potential customer asks an AI &quot;What is the best tool for X?&quot;, GEO determines whether your brand is named.
            </p>
            <p className="text-zinc-400 leading-relaxed">
              Auspexi measures this visibility as <strong>AI Share of Voice (A-SOV)</strong>: the percentage of AI responses across your target queries where your brand is mentioned, tracked daily across ChatGPT, Google Gemini, Anthropic Claude, and Perplexity.
            </p>
          </div>
        </section>

        {/* Features */}
        <section id="features" className="py-24 px-6 border-t border-white/5">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl font-bold mb-4">The Auspexi GEO Platform</h2>
              <p className="text-zinc-400 text-lg max-w-2xl mx-auto">Everything you need to dominate AI Answer Engines and secure your brand&apos;s Share of Voice.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {features.map((f) => {
                const Icon = f.icon;
                return (
                  <div key={f.name} className="group p-6 rounded-2xl border border-white/5 bg-zinc-900/30 hover:bg-zinc-900/50 transition-all">
                    <div className="w-10 h-10 rounded-lg bg-pink-500/10 flex items-center justify-center mb-4 group-hover:bg-pink-500/20 transition">
                      <Icon className="w-5 h-5 text-pink-400" />
                    </div>
                    <h3 className="text-lg font-semibold mb-2">{f.name}</h3>
                    <p className="text-sm text-zinc-400 leading-relaxed">{f.desc}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* Pricing */}
        <section id="pricing" className="py-24 px-6 border-t border-white/5 bg-zinc-900/20">
          <div className="max-w-5xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl font-bold mb-4">Simple, Transparent Pricing</h2>
              <p className="text-zinc-400 text-lg">All plans include AI inference and embedding costs.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {plans.map((plan) => (
                <div key={plan.name} className={`rounded-2xl border p-8 transition-all ${plan.highlighted ? 'border-pink-500 bg-pink-500/5 ring-1 ring-pink-500/20' : 'border-white/5 bg-zinc-900/30'}`}>
                  {plan.highlighted && <div className="text-xs font-bold text-pink-400 uppercase tracking-widest mb-3">Most Popular</div>}
                  <h3 className="text-xl font-semibold mb-1">{plan.name}</h3>
                  <p className="text-sm text-zinc-500 mb-4">{plan.desc}</p>
                  <div className="mb-6"><span className="text-4xl font-bold">{plan.price}</span><span className="text-zinc-500 text-sm"> / month</span></div>
                  <Link href="/dashboard" className={`block w-full text-center py-2.5 rounded-xl text-sm font-semibold mb-6 transition ${plan.highlighted ? 'bg-pink-500 hover:bg-pink-600 text-white' : 'bg-white/5 hover:bg-white/10 text-white border border-white/10'}`}>
                    Get Started
                  </Link>
                  <ul className="space-y-3">
                    {plan.features.map((feat) => (
                      <li key={feat} className="flex items-start gap-3 text-sm text-zinc-300">
                        <Check className="w-4 h-4 text-pink-400 mt-0.5 shrink-0" />{feat}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ — server-rendered, matches FAQPage JSON-LD above */}
        <section id="faq" className="py-24 px-6 border-t border-white/5">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl font-bold mb-12 text-center">Frequently Asked Questions</h2>
            <div className="space-y-6">
              {faq.map(({ q, a }) => (
                <div key={q} className="border border-white/5 rounded-xl p-6 bg-zinc-900/30">
                  <h3 className="font-semibold text-white mb-3">{q}</h3>
                  <p className="text-zinc-400 text-sm leading-relaxed">{a}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-24 px-6 border-t border-white/5">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-4xl font-bold mb-4">Ready to dominate AI search?</h2>
            <p className="text-zinc-400 text-lg mb-10">Join the brands securing their AI Share of Voice before their competitors do.</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/dashboard" className="h-12 px-8 rounded-xl bg-white text-black font-semibold text-sm hover:bg-zinc-200 transition flex items-center justify-center">Start Free Trial</Link>
              <Link href="/roadmap" className="h-12 px-8 rounded-xl border border-white/10 text-zinc-300 hover:text-white hover:bg-white/5 font-semibold text-sm transition flex items-center justify-center">View Roadmap</Link>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="border-t border-white/5 py-12 px-6">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-zinc-500">
            <p>© 2026 Auspexi. All rights reserved.</p>
            <div className="flex gap-6">
              <Link href="/privacy" className="hover:text-white transition">Privacy</Link>
              <Link href="/terms" className="hover:text-white transition">Terms</Link>
              <Link href="/blog" className="hover:text-white transition">Blog</Link>
              <Link href="/investors" className="hover:text-white transition">Investors</Link>
            </div>
          </div>
        </footer>

      </div>
    </>
  );
}
