'use client';

import { useState, useEffect, useMemo } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { authFetch } from '@/lib/auth-fetch';
import {
  FileQuestion, Sparkles, Copy, Check, Loader2, Code, FileText, Braces,
  Target, AlertCircle,
} from 'lucide-react';

// FAQ Architect — turns the user's probe history + Fact-Vault into a complete,
// deploy-ready FAQ page: visible HTML with per-question anchors, FAQPage
// JSON-LD, and markdown. The same structure we run on our own /faq page.

interface FaqItem { question: string; answer: string; source: string }
interface FaqCategory { id: string; title: string; description: string; items: FaqItem[] }
interface Draft {
  brand: string;
  domain: string;
  categories: FaqCategory[];
  stats: { totalQuestions: number; fromUncitedQueries: number; factCount: number; probeQueryCount: number };
  generatedAt: string;
}

const SOURCE_BADGES: Record<string, { label: string; cls: string }> = {
  'uncited-query':      { label: 'gap query',   cls: 'bg-rose-500/10 text-rose-400 border-rose-500/20' },
  'cited-query':        { label: 'won query',   cls: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' },
  'fact-vault':         { label: 'fact vault',  cls: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20' },
  'category-knowledge': { label: 'category',    cls: 'bg-zinc-500/10 text-zinc-400 border-zinc-500/20' },
};

function slugify(text: string): string {
  return text.toLowerCase().replace(/['']/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80);
}

function buildJsonLd(draft: Draft): string {
  const base = draft.domain ? `https://${draft.domain.replace(/^https?:\/\//, '').replace(/\/$/, '')}/faq` : '/faq';
  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: draft.categories.flatMap(cat => cat.items.map(item => ({
      '@type': 'Question',
      name: item.question,
      url: `${base}#${slugify(item.question)}`,
      acceptedAnswer: { '@type': 'Answer', text: item.answer },
    }))),
  }, null, 2);
}

function buildHtml(draft: Draft): string {
  const sections = draft.categories.map(cat => {
    const items = cat.items.map(item =>
      `    <div id="${slugify(item.question)}" style="scroll-margin-top:100px">\n` +
      `      <h3>${item.question}</h3>\n` +
      `      <p>${item.answer}</p>\n` +
      `    </div>`
    ).join('\n');
    return `  <section id="${cat.id}">\n    <h2>${cat.title}</h2>\n    <p>${cat.description}</p>\n${items}\n  </section>`;
  }).join('\n\n');
  return `<!-- FAQ generated by L8EntSpace FAQ Architect. Answers are in the DOM\n     on load (AI-crawlable) with per-question anchor ids for deep-link citations. -->\n<script type="application/ld+json">\n${buildJsonLd(draft)}\n</script>\n\n<main>\n  <h1>${draft.brand}: Frequently Asked Questions</h1>\n${sections}\n</main>`;
}

function buildMarkdown(draft: Draft): string {
  return `# ${draft.brand}: Frequently Asked Questions\n\n` +
    draft.categories.map(cat =>
      `## ${cat.title}\n\n${cat.description}\n\n` +
      cat.items.map(item => `### ${item.question}\n\n${item.answer}`).join('\n\n')
    ).join('\n\n');
}

type ExportTab = 'preview' | 'html' | 'jsonld' | 'markdown';

export default function FaqArchitectPage() {
  const { user } = useAuth();
  const [draft, setDraft] = useState<Draft | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<ExportTab>('preview');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!user?.uid) { setLoading(false); return; }
    (async () => {
      try {
        const res = await authFetch('/api/faq-architect');
        const json = await res.json();
        if (json.success && json.draft) setDraft(json.draft);
      } catch { /* ignore */ }
      finally { setLoading(false); }
    })();
  }, [user?.uid]);

  const generate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const res = await authFetch('/api/faq-architect', { method: 'POST' });
      const json = await res.json();
      if (json.success && json.draft) setDraft(json.draft);
      else setError(json.error || 'Generation failed');
    } catch (e: any) {
      setError(e.message);
    } finally {
      setGenerating(false);
    }
  };

  const exportContent = useMemo(() => {
    if (!draft) return '';
    if (tab === 'html') return buildHtml(draft);
    if (tab === 'jsonld') return `<script type="application/ld+json">\n${buildJsonLd(draft)}\n</script>`;
    if (tab === 'markdown') return buildMarkdown(draft);
    return '';
  }, [draft, tab]);

  const copy = async () => {
    await navigator.clipboard.writeText(exportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="space-y-6 max-w-5xl">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-pink-500/10 flex items-center justify-center">
            <FileQuestion className="w-5 h-5 text-pink-400" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-white">FAQ Architect</h1>
            <p className="text-xs text-zinc-500">FAQ page from your real probe queries and Fact-Vault, ready to deploy.</p>
          </div>
        </div>
        <button
          onClick={generate}
          disabled={generating}
          className="flex items-center gap-2 px-5 py-2.5 bg-pink-500 hover:bg-pink-400 disabled:opacity-50 text-white text-sm font-bold rounded-xl transition-colors shrink-0"
        >
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
          {generating ? 'Architecting…' : draft ? 'Regenerate' : 'Generate FAQ'}
        </button>
      </div>

      {error && (
        <div className="flex items-center gap-2 p-4 bg-rose-500/5 border border-rose-500/20 rounded-xl text-sm text-rose-300">
          <AlertCircle className="w-4 h-4 shrink-0" /> {error}
        </div>
      )}

      {loading && (
        <div className="flex items-center justify-center py-20 gap-3 text-zinc-500">
          <Loader2 className="w-4 h-4 animate-spin" /> <span className="text-sm">Loading…</span>
        </div>
      )}

      {!loading && !draft && !generating && (
        <div className="flex flex-col items-center text-center py-16 px-6 bg-zinc-900/40 border border-zinc-800 rounded-2xl">
          <Target className="w-8 h-8 text-zinc-700 mb-3" />
          <p className="text-sm font-semibold text-zinc-300">No FAQ draft yet</p>
          <p className="text-xs text-zinc-500 mt-2">Run a probe and add facts first, then generate.</p>
        </div>
      )}

      {draft && (
        <>
          {/* Stats strip */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: 'Questions', value: draft.stats.totalQuestions },
              { label: 'From Gap Queries', value: draft.stats.fromUncitedQueries },
              { label: 'Facts Used', value: draft.stats.factCount },
              { label: 'Probe Queries', value: draft.stats.probeQueryCount },
            ].map(s => (
              <div key={s.label} className="p-3 bg-zinc-900/40 border border-zinc-800 rounded-xl text-center">
                <p className="text-lg font-black text-white">{s.value}</p>
                <p className="text-[9px] text-zinc-500 uppercase tracking-widest">{s.label}</p>
              </div>
            ))}
          </div>

          {/* Export tabs */}
          <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl overflow-hidden">
            <div className="flex items-center justify-between border-b border-zinc-800">
              <div className="flex overflow-x-auto">
                {([
                  ['preview', 'Preview', FileQuestion],
                  ['html', 'HTML + Schema', Code],
                  ['jsonld', 'JSON-LD Only', Braces],
                  ['markdown', 'Markdown', FileText],
                ] as [ExportTab, string, any][]).map(([id, label, Icon]) => (
                  <button
                    key={id}
                    onClick={() => setTab(id)}
                    className={`flex items-center gap-1.5 px-4 py-3 text-xs font-bold whitespace-nowrap border-b-2 transition-colors ${
                      tab === id ? 'text-pink-400 border-pink-500 bg-pink-500/5' : 'text-zinc-500 border-transparent hover:text-zinc-300'
                    }`}
                  >
                    <Icon className="w-3.5 h-3.5" /> {label}
                  </button>
                ))}
              </div>
              {tab !== 'preview' && (
                <button
                  onClick={copy}
                  className="flex items-center gap-1.5 px-3 py-1.5 mr-3 text-xs font-bold text-zinc-300 bg-zinc-800 hover:bg-zinc-700 rounded-lg transition-colors shrink-0"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
              )}
            </div>

            <div className="p-5">
              {tab === 'preview' ? (
                <div className="space-y-8">
                  {draft.categories.map(cat => (
                    <section key={cat.id}>
                      <h2 className="text-sm font-bold text-white">{cat.title}</h2>
                      <p className="text-xs text-zinc-500 mb-3">{cat.description}</p>
                      <div className="space-y-2">
                        {cat.items.map((item, i) => {
                          const badge = SOURCE_BADGES[item.source] ?? SOURCE_BADGES['category-knowledge'];
                          return (
                            <div key={i} className="p-4 bg-zinc-950 border border-zinc-800/60 rounded-xl">
                              <div className="flex items-start justify-between gap-3">
                                <p className="text-sm font-semibold text-zinc-100">{item.question}</p>
                                <span className={`shrink-0 px-2 py-0.5 rounded-full text-[9px] font-bold uppercase border ${badge.cls}`}>
                                  {badge.label}
                                </span>
                              </div>
                              <p className="text-xs text-zinc-400 leading-relaxed mt-1.5">{item.answer}</p>
                            </div>
                          );
                        })}
                      </div>
                    </section>
                  ))}
                </div>
              ) : (
                <pre className="text-[11px] text-zinc-300 font-mono whitespace-pre-wrap break-words max-h-[560px] overflow-y-auto leading-relaxed">
                  {exportContent}
                </pre>
              )}
            </div>
          </div>

          <p className="text-[10px] text-zinc-600">Generated {new Date(draft.generatedAt).toLocaleString()}.</p>
        </>
      )}
    </div>
  );
}
